// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file health.proto (package proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file health.proto.
 */
export const file_health: GenFile = /*@__PURE__*/
  fileDesc("CgxoZWFsdGgucHJvdG8SBXByb3RvIg8KDUhlYWx0aFJlcXVlc3QiPAoOSGVhbHRoUmVzcG9uc2USDgoGc3RhdHVzGAEgASgJEhoKEnBvc3RncmVzX2RiX3N0YXR1cxgCIAEoCTJFCg1IZWFsdGhTZXJ2aWNlEjQKBUNoZWNrEhQucHJvdG8uSGVhbHRoUmVxdWVzdBoVLnByb3RvLkhlYWx0aFJlc3BvbnNlQkhaRmdpdGh1Yi5jb20vQWthc2gtTWFuaWthbmRhbi9hcHAtYmFja2VuZC9pbnRlcm5hbC9tb2R1bGVzL2hlYWx0aDtoZWFsdGhiBnByb3RvMw");

/**
 * HealthRequest represents a request to check the health status of the service
 *
 * @generated from message proto.HealthRequest
 */
export type HealthRequest = Message<"proto.HealthRequest"> & {
};

/**
 * Describes the message proto.HealthRequest.
 * Use `create(HealthRequestSchema)` to create a new message.
 */
export const HealthRequestSchema: GenMessage<HealthRequest> = /*@__PURE__*/
  messageDesc(file_health, 0);

/**
 * HealthResponse represents the health status response from the service
 *
 * @generated from message proto.HealthResponse
 */
export type HealthResponse = Message<"proto.HealthResponse"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * @generated from field: string postgres_db_status = 2;
   */
  postgresDbStatus: string;
};

/**
 * Describes the message proto.HealthResponse.
 * Use `create(HealthResponseSchema)` to create a new message.
 */
export const HealthResponseSchema: GenMessage<HealthResponse> = /*@__PURE__*/
  messageDesc(file_health, 1);

/**
 * HealthService provides health check functionality for the service
 *
 * @generated from service proto.HealthService
 */
export const HealthService: GenService<{
  /**
   * Check returns the health status of the service
   *
   * @generated from rpc proto.HealthService.Check
   */
  check: {
    methodKind: "unary";
    input: typeof HealthRequestSchema;
    output: typeof HealthResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_health, 0);

